# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteings', to=settings.AUTH_USER_MODEL),
        ),
    ]
