# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteings', '0002_auto_20171113_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteing',
            old_name='user',
            new_name='creator',
        ),
    ]
